events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream removi_app {
        server app:${APP_PORT};
    }

    server {
        listen ${NGINX_PORT};
        server_name _;

        location / {
            proxy_pass http://removi_app;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
