events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream removi_app {
        server app:${APP_PORT};
    }

    server {
        listen ${NGINX_HTTPS_PORT} ssl;
        http2 on;
        server_name ${SITE_DOMAIN};

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_pass http://removi_app;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen ${NGINX_HTTP_PORT};
        server_name ${SITE_DOMAIN};
        return 301 https://$host$request_uri;
    }
}