(function () {
  const SETTINGS = { initial: 30, batch: 10, max: 60 };
  const DEFAULT_MESSAGES = {
    login: '⚠ Неверный логин или пароль',
    register: '⚠ Пожалуйста, заполните все поля'
  };

  const FILTERS = [
    { key: 'all', label: 'Все' },
    { key: 'ambient', label: 'Ambient' },
    { key: 'phonk', label: 'Phonk' },
    { key: 'hyperpop', label: 'Hyperpop' },
    { key: 'house', label: 'House' },
    { key: 'trap', label: 'Trap' },
    { key: 'cinematic', label: 'Cinematic' },
    { key: 'lofi', label: 'Lo-Fi' },
    { key: 'techno', label: 'Techno' },
    { key: 'synthwave', label: 'Synthwave' }
  ];

  const CATEGORY_THEMES = {
    all: { label: 'Все', colors: ['#111115', '#252532'], accent: '#ff8c42', mark: '◉' },
    ambient: { label: 'Ambient', colors: ['#0c1422', '#234d64'], accent: '#7dd3fc', mark: '☁' },
    phonk: { label: 'Phonk', colors: ['#120c12', '#6b1d1d'], accent: '#fb7185', mark: '◈' },
    hyperpop: { label: 'Hyperpop', colors: ['#1a1020', '#db2777'], accent: '#f9a8d4', mark: '✦' },
    house: { label: 'House', colors: ['#1a120d', '#ea580c'], accent: '#fdba74', mark: '▣' },
    trap: { label: 'Trap', colors: ['#111418', '#374151'], accent: '#d1d5db', mark: '▲' },
    cinematic: { label: 'Cinematic', colors: ['#120f0d', '#7c2d12'], accent: '#f59e0b', mark: '▶' },
    lofi: { label: 'Lo-Fi', colors: ['#16131c', '#475569'], accent: '#c4b5fd', mark: '◌' },
    techno: { label: 'Techno', colors: ['#07131b', '#0f766e'], accent: '#67e8f9', mark: '⌘' },
    synthwave: { label: 'Synthwave', colors: ['#170f1f', '#7e22ce'], accent: '#f472b6', mark: '◎' }
  };

  const STOP_WORDS = new Set([
    'track', 'edit', 'mix', 'ver', 'version', 'for', 'the', 'and', 'with', 'from',
    'для', 'после', 'перед', 'или', 'under', 'sobre', 'para', 'dans', 'with', 'without',
    'removi', 'ai', 'generated', 'audio', 'composition', 'release', 'session'
  ]);

  const AUTHOR_PARTS = {
    first: ['Ari', 'Mila', 'Naomi', 'Yuto', 'Sora', 'Noa', 'Lina', 'Matteo', 'Léo', 'Ivy', 'Mira', 'Akira', 'Elio', 'Kira', 'Nina', 'Taiga', 'Clara', 'Noor', 'Yana', 'Rin'],
    last: ['Vale', 'Sato', 'Marlow', 'Noir', 'Kline', 'Aster', 'Velour', 'Mori', 'Bloom', 'Serrin', 'Kestrel', 'Ibarra', 'Vega', 'Solari', 'Drift', 'Lune', 'Ortega', 'Sable'],
    nickLeft: ['midnight', 'sub', 'nova', 'silk', 'drift', 'echo', 'mono', 'lucid', 'static', 'velvet', 'broken', 'night', 'haze', 'zero', 'chrome', 'after'],
    nickRight: ['signal', 'child', 'routine', 'club', 'season', 'cassette', 'district', 'mirror', 'engine', 'hotel', 'archive', 'tempo', 'vista', 'driver', 'shape', 'room']
  };

  const DATES = ['2 часа назад', '5 часов назад', 'вчера', '2 дня назад', '3 дня назад', 'неделю назад', '2 недели назад', 'месяц назад', '2 месяца назад'];
  const QUALS = ['LOSSLESS', 'HQ', '320K', ''];
  const CATEGORY_SEQUENCE = ['ambient', 'phonk', 'hyperpop', 'house', 'trap', 'cinematic', 'lofi', 'techno', 'synthwave'];

  const GENRE_COPY = {
    ambient: {
      actions: ['AI composed', 'Нейросеть собрала', 'Generated by REMOVI', 'Algoritmo creó'],
      subjects: ['Northern Delay', 'Glass Morning', 'Lento Horizonte', 'Тихий дрейф', 'Blue Terminal', 'Poussière de nuit'],
      tails: ['for empty terminals', 'для холодного рассвета', 'sobre la ciudad dormida', 'after the last rain', 'in low cloud motion', 'pour les couloirs sans fin'],
      styles: ['Ambient Session', 'sleep edit', 'drift mix', 'field render'],
      openings: ['держится на длинных пэдах и прозрачном воздухе', 'работает как мягкий саундтрек к пустому пространству', 'создает ощущение медленного движения внутри света'],
      textures: ['ледяной реверберацией, тихими гармониями и далекими шумами', 'тонким дроуном, пылью синтов и почти невесомым ритмом', 'медленным дыханием текстур и мягким спектром верхов'],
      focuses: ['послевкусии тишины', 'атмосфере пустого города', 'ощущении застывшего времени']
    },
    phonk: {
      actions: ['AI dropped', 'Нейросеть уронила', 'Generated by REMOVI', 'Machine built'],
      subjects: ['Midnight Tire Smoke', 'Кассета без тормозов', 'Rua Fantasma', 'Chrome Memphis', 'Last Exit 95', 'No Mercy Drift'],
      tails: ['under red lights', 'для бетонной ночи', 'with burned bass', 'sur les lignes sales', 'for the final corner', 'in trunk-rattle mode'],
      styles: ['street edit', 'drift version', 'night tape', 'club cut'],
      openings: ['забирает грязным басом и резким качем', 'собирает ночь через перегруженный грув и кассетную пыль', 'работает как уличный релиз для пустой магистрали'],
      textures: ['плотным sub-басом, клиппингом и резким cowbell-паттерном', 'дымной сатурацией, короткими хуками и сырым давлением', 'грязным низом, ломаным качем и мемфис-сэмплами'],
      focuses: ['ночном драйве', 'ощущении скорости без камеры', 'уличной энергии позднего часа']
    },
    hyperpop: {
      actions: ['AI exploded into', 'Нейросеть собрала', 'Generated by REMOVI', 'Engine rendered'],
      subjects: ['Plastic Hearts.exe', 'Neon Sugar Fall', 'Ошибка на танцполе', 'Bubble Damage', 'Ultra Soft Panic', 'Amor digital'],
      tails: ['with chrome vocals', 'в режиме перегруза', 'after the pink crash', 'para una fiesta sin sueño', 'inside mirror candy', 'dans le flash total'],
      styles: ['hyper edit', 'bubble mix', 'gloss version', 'club render'],
      openings: ['работает через цифровую сладость и предельный перегруз', 'звучит как поп-хук после столкновения с глитчем', 'собирает яркий синтетический удар без пауз'],
      textures: ['переломанными вокальными слоями, глянцевыми синтами и вспышками distortion', 'сверхярким верхом, пластиковой мелодикой и резким ритмом', 'сахарным лидом, цифровым хрупом и быстрым переходом'],
      focuses: ['моментальном хуке', 'чувстве искусственной эйфории', 'ярком цифровом блеске релиза']
    },
    house: {
      actions: ['AI mixed', 'Нейросеть свела', 'Generated by REMOVI', 'Machine pressed'],
      subjects: ['Afterhours on Marble Floor', 'Casa de cristal', 'Город дышит ровно', 'Velvet Lobby', 'Sunset Lift', 'Room Service Groove'],
      tails: ['for the long fade', 'в одном теплом цикле', 'under rooftop lights', 'para las cuatro утра', 'inside a soft kick loop', 'after the first sip'],
      styles: ['club mix', 'late cut', 'extended club', 'warm edit'],
      openings: ['держится на ровном груве и мягком движении баса', 'работает как поздний клубный релиз с чистой подачей', 'собирает теплую пульсацию без суеты'],
      textures: ['четкой бочкой, стеклянными аккордами и плавным сабом', 'круглым басом, коротким вокальным шлейфом и теплой перкуссией', 'ровным качем, мягким синтом и просторной серединой'],
      focuses: ['чистом клубном ходе', 'плавном телесном ритме', 'ощущении длинной ночной петли']
    },
    trap: {
      actions: ['AI loaded', 'Нейросеть собрала', 'Generated by REMOVI', 'System built'],
      subjects: ['Black Rain Routine', 'После полуночи без сна', 'Monochrome Flex', 'No Sleep Balcony', 'Late Code Prayer', 'Piso oscuro'],
      tails: ['with cold 808s', 'для ледяного бита', 'under black skylines', 'after the missed call', 'con humo digital', 'for low light speakers'],
      styles: ['night cut', '808 version', 'cold mix', 'after dark edit'],
      openings: ['опирается на тяжелый 808 и холодный простор', 'звучит как ночной релиз с напряженной паузой между ударами', 'строится на темном ритме и сухом ударе снейра'],
      textures: ['длинным сабом, редким хэтом и плотным воздухом куплета', 'стеклянным верхом, медленным свингом и сухой атакой', 'холодным 808, приглушенным лидом и поздней мелодикой'],
      focuses: ['тягучем ночном напряжении', 'пространстве между ударами', 'ощущении позднего большого города']
    },
    cinematic: {
      actions: ['AI scored', 'Нейросеть написала', 'Generated by REMOVI', 'Orchestra engine built'],
      subjects: ['Ashes Over The Observatory', 'Последний кадр без диалогов', 'La chambre des ombres', 'Signal Before The Fall', 'Velvet Catastrophe', 'Orquesta del eclipse'],
      tails: ['for a film that does not exist', 'для финальной сцены', 'before the title drop', 'sur le dernier plan', 'after the silent cut', 'con la ciudad en ruinas'],
      styles: ['score version', 'trailer edit', 'final cue', 'orchestral cut'],
      openings: ['работает как саундтрек к большому вымышленному кадру', 'звучит как финальная тема для несуществующего фильма', 'держится на драме пространства и размахе аранжировки'],
      textures: ['широкими струнными, медью и нарастающим ударом', 'оркестровым воздухом, гулом низов и резким подъемом динамики', 'большим ревёрбом, кинематографической паузой и масштабным акцентом'],
      focuses: ['ощущении кульминации', 'эмоциональном размахе', 'чувстве финального разворота сцены']
    },
    lofi: {
      actions: ['AI looped', 'Нейросеть собрала', 'Generated by REMOVI', 'Tape engine wrote'],
      subjects: ['Rain on the Study Lamp', 'Кофе, окно и пленка', 'Dormir con ruido azul', 'Soft Notes For Late Homework', 'Appartement 302', 'Notebook After Midnight'],
      tails: ['for quiet evenings', 'для долгой переписки', 'under tape hiss', 'after homework hours', 'con luces bajas', 'pour une pluie lente'],
      styles: ['tape mix', 'soft loop', 'study edit', 'cassette cut'],
      openings: ['собирает мягкий пульс для позднего спокойного фона', 'работает как теплая петля для долгого вечера', 'держится на кассетной пыли и мягкой мелодике'],
      textures: ['шорохом ленты, джазовым аккордом и теплым битом', 'тихой ударной петлей, мягким Rhodes и пленочным шумом', 'пыльным верхом, домашней комнатной атмосферой и расслабленным грувом'],
      focuses: ['спокойной концентрации', 'чувстве домашнего света', 'тихом позднем ритме']
    },
    techno: {
      actions: ['AI sequenced', 'Нейросеть собрала', 'Generated by REMOVI', 'Machine synced'],
      subjects: ['Control Room Pulse', 'После третьего строба', 'Nachtprotokoll', 'Static Warehouse', 'Impulse 143', 'Ciudad industrial'],
      tails: ['under pressure lights', 'для бетонного зала', 'in warehouse mode', 'nach dem signal', 'con pulso mecánico', 'after no sleep'],
      styles: ['warehouse cut', 'club pressure', 'sequence edit', 'floor version'],
      openings: ['идет через жесткую секвенцию и стальной моторный ритм', 'работает как клубный трек для темного индустриального зала', 'держится на механическом импульсе и давлении грува'],
      textures: ['жесткой бочкой, сухой перкуссией и сверлящим синтом', 'стальным киком, повтором арпеджио и давящим драйвом', 'плотной секвенцией, холодным шумом и прямым импульсом'],
      focuses: ['непрерывном моторном ходе', 'давлении ритма на тело', 'чистом индустриальном гипнозе']
    },
    synthwave: {
      actions: ['AI transmitted', 'Нейросеть собрала', 'Generated by REMOVI', 'Engine rendered'],
      subjects: ['Sunset Error 1987', 'Неоновый отель у шоссе', 'Velocidad rosa', 'Afterglow Driver', 'Tokyo Mirage Night', 'Ligne violette'],
      tails: ['for the last night drive', 'под фиолетовый горизонт', 'with chrome nostalgia', 'para una autopista vacía', 'sur la ligne rose', 'after the city fades'],
      styles: ['night drive mix', 'neon cut', 'retro edit', 'afterglow version'],
      openings: ['строится на ностальгическом драйве и ясной синт-линии', 'звучит как ночная поездка по неоновому шоссе', 'держит баланс между ретро-мелодикой и плотным современным ударом'],
      textures: ['широкими пэдами, ретро-барабанами и стеклянным лидом', 'неоновым басом, арпеджио и теплым цифровым свечением', 'пурпурным воздухом синтов, мягким kick и длинным afterglow'],
      focuses: ['ночной дороге без конца', 'ощущении красивой синтетической ностальгии', 'неоновом движении сквозь пустой город']
    }
  };

  const PREVIEW_BANK = {
    ambient: {
      heads: ['ЭТО СЛИШКОМ КРАСИВО ДЛЯ ФОНА', 'ЭТОТ ТРЕК УСПОКАИВАЕТ СРАЗУ', 'ОДИН ПАД И УЖЕ ТИШЕ'],
      subs: ['после этого комната звучит иначе', 'здесь воздух важнее бита', 'трек держится на чистом пространстве']
    },
    phonk: {
      heads: ['ЭТОТ BASS ЛОМАЕТ ТИШИНУ', 'ПОСЛЕ ЭТОГО НУЖЕН НОЧНОЙ ЗАЕЗД', 'ЭТА КАССЕТА ДАВИТ КАК НАДО'],
      subs: ['грязный кач включается сразу', 'один drop и уже поздно', 'так звучит пустая магистраль']
    },
    hyperpop: {
      heads: ['ЭТОТ ХУК ВЛЕТАЕТ СРАЗУ', 'ТАКОЙ ПРИПЕВ НЕ ОТПУСКАЕТ', 'ЭТО СЛИШКОМ ЯРКО ЧТОБЫ ПРОПУСТИТЬ'],
      subs: ['все блестит и ломается вовремя', 'перегруз здесь только украшает', 'треки такого типа цепляют с первой секунды']
    },
    house: {
      heads: ['ЭТОТ ГРУВ РАБОТАЕТ БЕЗ ОШИБОК', 'ПОСЛЕ ЭТОГО ХОЧЕТСЯ ПРОДЛИТЬ НОЧЬ', 'ЧИСТЫЙ HOUSE С ПЕРВОГО УДАРА'],
      subs: ['ровный кач держит весь трек', 'здесь все собрано вокруг движения', 'так звучит поздний клуб без суеты']
    },
    trap: {
      heads: ['ЭТОТ 808 СЛИШКОМ ТЯЖЕЛЫЙ', 'ПОСЛЕ ЭТОГО БИТ НЕ ОТПУСТИТ', 'НОЧНОЙ TRAP В ЧИСТОМ ВИДЕ'],
      subs: ['весь вес в одном низе', 'пауза здесь работает как оружие', 'это звучит холодно и точно']
    },
    cinematic: {
      heads: ['ТАК ЗВУЧИТ ФИНАЛ БОЛЬШОЙ СЦЕНЫ', 'ЭТОТ SCORE УЖЕ ПРОДАЕТ ФИЛЬМ', 'ПОСЛЕ ЭТОГО НУЖЕН ЦЕЛЫЙ СЮЖЕТ'],
      subs: ['один трек и уже ощущение титров', 'здесь драма появляется сразу', 'масштаб слышен с первого движения']
    },
    lofi: {
      heads: ['ЭТОТ LOOP ВКЛЮЧАЕТ ВЕЧЕР', 'ПОСЛЕ ЭТОГО ХОЧЕТСЯ ЗАКРЫТЬ НОУТ', 'МЯГКИЙ БИТ ДЛЯ ДОЛГОЙ НОЧИ'],
      subs: ['шорох пленки здесь все решает', 'трек дышит очень спокойно', 'идеально для тихого фонового режима']
    },
    techno: {
      heads: ['ЭТОТ КИК НЕВОЗМОЖНО ИГНОРИРОВАТЬ', 'ПОСЛЕ ЭТОГО СТРОБ БЬЕТ ТОЧНЕЕ', 'ПРЯМОЙ ТЕХНО-УДАР БЕЗ ПАУЗ'],
      subs: ['ритм тянет дальше сам', 'это чистое давление секвенции', 'складской зал уже слышен']
    },
    synthwave: {
      heads: ['ЭТОТ ТРЕК ПРОСИТ НОЧНОЕ ШОССЕ', 'НЕОН СЛЫШЕН С ПЕРВОЙ НОТЫ', 'ПОСЛЕ ЭТОГО ХОЧЕТСЯ ЕХАТЬ ДАЛЬШЕ'],
      subs: ['ностальгия включается моментально', 'весь трек светится фиолетовым', 'это уже саундтрек к ночному городу']
    }
  };

  function hashString(value) {
    let hash = 2166136261;
    for (let index = 0; index < value.length; index += 1) {
      hash ^= value.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    return hash >>> 0;
  }

  function normalizeText(value) {
    return String(value || '').toLowerCase().replace(/ё/g, 'е');
  }

  function escapeHtml(value) {
    return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function clampText(value, max) {
    return value.length > max ? `${value.slice(0, max - 1)}…` : value;
  }

  function shuffle(list) {
    const copy = [...list];
    for (let index = copy.length - 1; index > 0; index -= 1) {
      const swapIndex = Math.floor(Math.random() * (index + 1));
      [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
    }
    return copy;
  }

  function pick(list, seed, offset = 0) {
    return list[(seed + offset) % list.length];
  }

  function buildAuthor(id) {
    const first = AUTHOR_PARTS.first[(id * 7 + 3) % AUTHOR_PARTS.first.length];
    const last = AUTHOR_PARTS.last[(id * 11 + 5) % AUTHOR_PARTS.last.length];
    const nickLeft = AUTHOR_PARTS.nickLeft[(id * 13 + 1) % AUTHOR_PARTS.nickLeft.length];
    const nickRight = AUTHOR_PARTS.nickRight[(id * 17 + 2) % AUTHOR_PARTS.nickRight.length];
    const patterns = [
      `${first} ${last}`,
      `${nickLeft}.${nickRight}`,
      `${first} ${nickRight}`,
      `${nickLeft}_${nickRight}`,
      `${first}/${last}`,
      `${nickLeft}${(id % 71) + 17}`,
      `${first} ${last}-${(id % 9) + 1}`,
      `${nickLeft}.${nickRight}.wav`
    ];
    return patterns[id % patterns.length];
  }

  function buildAvatar(author) {
    const match = String(author).match(/[A-Za-zА-Яа-я0-9]/u);
    return match ? match[0].toUpperCase() : 'R';
  }

  function buildDurationPool(count) {
    return Array.from({ length: count }, (_, index) => 52 + ((index * 97 + 31) % 565));
  }

  function formatDuration(totalSeconds) {
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${String(seconds).padStart(2, '0')}`;
  }

  function extractMeaningfulWords(title) {
    return title
      .replace(/[«»"!?.,:;()—–/\\-]/g, ' ')
      .split(/\s+/)
      .map((part) => part.trim())
      .filter(Boolean)
      .filter((word) => word.length > 2 && !STOP_WORDS.has(normalizeText(word)));
  }

  function buildTitle(category, localIndex, id) {
    const source = GENRE_COPY[category];
    const seed = hashString(`${category}-${localIndex}-${id}`);
    const action = pick(source.actions, seed);
    const subject = source.subjects[localIndex % source.subjects.length];
    const tail = pick(source.tails, seed >>> 2, localIndex);
    const style = pick(source.styles, seed >>> 4, id);
    const templates = [
      `${subject} / ${style}`,
      `${action} ${subject} ${tail}`,
      `${subject} ${tail}`,
      `${subject}: ${style}`,
      `${action} ${subject}`
    ];
    return clampText(templates[id % templates.length], 104);
  }

  function buildTopicPhrase(title, category) {
    const words = extractMeaningfulWords(title);
    return (words.slice(0, 2).join(' ') || CATEGORY_THEMES[category].label).toLowerCase();
  }

  function buildPreviewCopy(title, category, id) {
    const bank = PREVIEW_BANK[category] || PREVIEW_BANK.lofi;
    const seed = hashString(`${title}-${category}-${id}`);
    return {
      headline: clampText(bank.heads[seed % bank.heads.length], 30),
      subline: clampText(bank.subs[(seed >>> 3) % bank.subs.length], 34)
    };
  }

  function splitPreviewText(value, maxChars, maxLines = 2) {
    const words = String(value).split(/\s+/).filter(Boolean);
    const lines = [];
    let current = '';
    for (const word of words) {
      const next = current ? `${current} ${word}` : word;
      if (next.length <= maxChars) {
        current = next;
        continue;
      }
      if (current) lines.push(current);
      current = word;
      if (lines.length === maxLines - 1) break;
    }
    if (lines.length < maxLines && current) lines.push(current);
    if (!lines.length) lines.push(clampText(value, maxChars));
    const visible = lines.slice(0, maxLines);
    if (words.join(' ').length > visible.join(' ').length) {
      visible[visible.length - 1] = clampText(visible[visible.length - 1], maxChars);
    }
    return visible;
  }

  function renderSvgLines(lines, x, y, options = {}) {
    const {
      fill = '#f8fafc',
      size = 18,
      weight = 700,
      lineHeight = 20,
      opacity = 1
    } = options;
    return `<text x="${x}" y="${y}" fill="${fill}" fill-opacity="${opacity}" font-family="Arial, sans-serif" font-size="${size}" font-weight="${weight}">${lines.map((line, index) => `<tspan x="${x}" dy="${index === 0 ? 0 : lineHeight}">${escapeHtml(line)}</tspan>`).join('')}</text>`;
  }

  function buildViews(id, title, dateLabel) {
    const hash = hashString(`${title}-${id}-${dateLabel}`);
    const ranges = {
      '2 часа назад': [10, 900],
      '5 часов назад': [20, 1400],
      'вчера': [60, 3200],
      '2 дня назад': [80, 5200],
      '3 дня назад': [100, 7000],
      'неделю назад': [120, 11000],
      '2 недели назад': [150, 13000],
      'месяц назад': [180, 15000],
      '2 месяца назад': [90, 15000]
    };
    const [min, max] = ranges[dateLabel] || [50, 8000];
    return new Intl.NumberFormat('ru-RU').format(min + (hash % (max - min + 1)));
  }

  function buildPlayerExcerpt(title, author, category, id) {
    const source = GENRE_COPY[category];
    const seed = hashString(`${title}-${author}-${category}-${id}`);
    const opener = pick(source.openings, seed, id);
    const texture = pick(source.textures, seed >>> 3, id * 2);
    const focus = pick(source.focuses, seed >>> 5, id * 3);
    const closers = [
      'В итоге релиз ощущается как законченная AI-композиция, а не как тест генератора.',
      'Из-за этого трек воспринимается как самостоятельный сингл с ясной драматургией.',
      'Поэтому композиция держит внимание не только саунд-дизайном, но и собственным настроением.',
      'Так трек складывается в цельный релиз с понятной атмосферой и музыкальной логикой.',
      'За счет этого композиция звучит как часть убедимого каталога синтетической музыки REMOVI.'
    ];
    return `«${title}» — AI-композиция автора ${author}. Этот релиз ${opener}. Трек держится на ${texture}. В центре внимания ${buildTopicPhrase(title, category)} и ${focus}. ${closers[(seed >>> 7) % closers.length]}`;
  }

  function buildLocalPreviewPath(id) {
    return `assets/previews/audio-${String(id).padStart(3, '0')}.svg`;
  }

  function buildScene(category, theme, seed) {
    const horizon = 132 + (seed % 20);
    switch (category) {
      case 'ambient':
        return `<path d="M0 ${horizon + 44}C88 ${horizon - 12} 176 ${horizon - 18} 248 ${horizon + 12}S404 ${horizon + 58} 480 ${horizon + 24}V270H0Z" fill="rgba(255,255,255,0.1)"/><path d="M42 ${horizon + 10}C104 ${horizon - 20} 182 ${horizon - 8} 246 ${horizon + 14}" fill="none" stroke="rgba(255,255,255,0.16)" stroke-width="8" stroke-linecap="round"/>`;
      case 'phonk':
        return `<rect x="46" y="${horizon + 30}" width="388" height="52" rx="18" fill="rgba(8,8,12,0.56)"/><path d="M76 ${horizon + 64}L138 ${horizon + 40}L204 ${horizon + 48}L276 ${horizon + 24}L344 ${horizon + 60}" fill="none" stroke="${theme.accent}" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><circle cx="384" cy="${horizon + 54}" r="30" fill="rgba(255,255,255,0.1)"/>`;
      case 'hyperpop':
        return `<circle cx="154" cy="${horizon + 18}" r="44" fill="rgba(255,255,255,0.14)"/><circle cx="228" cy="${horizon + 54}" r="34" fill="${theme.accent}" opacity="0.28"/><circle cx="316" cy="${horizon + 32}" r="52" fill="rgba(255,255,255,0.08)"/><path d="M106 ${horizon + 96}C154 ${horizon + 56} 212 ${horizon + 58} 264 ${horizon + 96}" fill="none" stroke="rgba(255,255,255,0.18)" stroke-width="10" stroke-linecap="round"/>`;
      case 'house':
        return `<rect x="74" y="${horizon + 18}" width="232" height="92" rx="18" fill="rgba(10,10,14,0.54)" stroke="rgba(255,255,255,0.14)"/><g fill="rgba(255,255,255,0.9)"><rect x="96" y="${horizon + 34}" width="16" height="48" rx="4"/><rect x="120" y="${horizon + 26}" width="16" height="56" rx="4"/><rect x="144" y="${horizon + 18}" width="16" height="64" rx="4"/><rect x="168" y="${horizon + 30}" width="16" height="52" rx="4"/><rect x="192" y="${horizon + 22}" width="16" height="60" rx="4"/><rect x="216" y="${horizon + 34}" width="16" height="48" rx="4"/><rect x="240" y="${horizon + 18}" width="16" height="64" rx="4"/></g>`;
      case 'trap':
        return `<path d="M72 ${horizon + 96}L126 ${horizon + 26}L188 ${horizon + 88}L244 ${horizon + 36}L316 ${horizon + 94}L390 ${horizon + 20}" fill="none" stroke="rgba(255,255,255,0.18)" stroke-width="11" stroke-linecap="round" stroke-linejoin="round"/><rect x="54" y="${horizon + 102}" width="372" height="12" rx="6" fill="rgba(255,255,255,0.12)"/>`;
      case 'cinematic':
        return `<rect x="64" y="${horizon + 8}" width="168" height="110" rx="18" fill="rgba(10,10,12,0.62)" stroke="rgba(255,255,255,0.12)"/><path d="M246 ${horizon + 34}L420 ${horizon + 12}L420 ${horizon + 114}L246 ${horizon + 92}Z" fill="rgba(255,255,255,0.08)"/><circle cx="144" cy="${horizon + 62}" r="28" fill="rgba(255,255,255,0.12)"/>`;
      case 'lofi':
        return `<rect x="92" y="${horizon + 12}" width="150" height="116" rx="16" fill="rgba(255,255,255,0.1)"/><rect x="114" y="${horizon + 36}" width="106" height="68" rx="10" fill="rgba(255,255,255,0.18)"/><circle cx="336" cy="${horizon + 54}" r="38" fill="rgba(255,255,255,0.12)"/>`;
      case 'techno':
        return `<circle cx="194" cy="${horizon + 52}" r="54" fill="none" stroke="rgba(255,255,255,0.14)" stroke-width="10"/><circle cx="194" cy="${horizon + 52}" r="26" fill="rgba(255,255,255,0.14)"/><path d="M274 ${horizon + 12}H404M274 ${horizon + 52}H438M274 ${horizon + 92}H404" fill="none" stroke="${theme.accent}" stroke-width="8" stroke-linecap="round"/>`;
      case 'synthwave':
      default:
        return `<circle cx="344" cy="${horizon + 12}" r="56" fill="rgba(255,255,255,0.12)"/><path d="M92 ${horizon + 94}H402" fill="none" stroke="rgba(255,255,255,0.2)" stroke-width="10" stroke-linecap="round"/><path d="M120 ${horizon + 28}L168 ${horizon + 76}L222 ${horizon + 18}L278 ${horizon + 70}L334 ${horizon + 10}" fill="none" stroke="${theme.accent}" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
  }

  function buildPreviewSvgMarkup(card) {
    const theme = CATEGORY_THEMES[card.category];
    const seed = hashString(`${card.id}-${card.title}-${card.author}`);
    const previewCopy = buildPreviewCopy(card.title, card.category, card.id);
    const headlineLines = splitPreviewText(previewCopy.headline, 18, 2);
    const sublineLines = splitPreviewText(previewCopy.subline, headlineLines.length > 1 ? 24 : 30, 1);
    const headlineSvg = renderSvgLines(headlineLines, 24, 198, { size: 19, weight: 800, lineHeight: 22 });
    const sublineY = 226 + ((headlineLines.length - 1) * 22);
    const sublineSvg = renderSvgLines(sublineLines, 24, sublineY, { size: 13, weight: 600, fill: 'rgba(248,250,252,0.92)' });
    return `
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 270" preserveAspectRatio="xMidYMid slice">
        <defs>
          <linearGradient id="bg-${card.id}" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stop-color="${theme.colors[0]}"/><stop offset="100%" stop-color="${theme.colors[1]}"/>
          </linearGradient>
          <linearGradient id="panel-${card.id}" x1="0" y1="1" x2="0" y2="0">
            <stop offset="0%" stop-color="rgba(6,8,12,0.94)"/><stop offset="100%" stop-color="rgba(6,8,12,0.02)"/>
          </linearGradient>
        </defs>
        <rect width="480" height="270" fill="url(#bg-${card.id})"/>
        <circle cx="${92 + (seed % 280)}" cy="${54 + (seed % 56)}" r="${24 + (seed % 18)}" fill="${theme.accent}" opacity="0.18"/>
        ${buildScene(card.category, theme, seed)}
        <rect y="164" width="480" height="106" fill="url(#panel-${card.id})"/>
        <rect x="18" y="18" width="104" height="24" rx="12" fill="rgba(10,10,12,0.42)" stroke="rgba(255,255,255,0.08)"/>
        <text x="70" y="34" fill="rgba(255,255,255,0.9)" font-family="Arial, sans-serif" font-size="11" font-weight="700" text-anchor="middle" letter-spacing="1">${escapeHtml(theme.label.toUpperCase())}</text>
        ${headlineSvg}
        ${sublineSvg}
        <text x="430" y="244" fill="rgba(255,255,255,0.9)" font-family="Arial, sans-serif" font-size="22" text-anchor="end">${escapeHtml(theme.mark)}</text>
      </svg>
    `;
  }

  const durationPool = buildDurationPool(120);
  const counters = Object.fromEntries(CATEGORY_SEQUENCE.map((category) => [category, 0]));
  const ALL_CARDS = Array.from({ length: 100 }, (_, id) => {
    const category = CATEGORY_SEQUENCE[id % CATEGORY_SEQUENCE.length];
    const localIndex = counters[category];
    counters[category] += 1;
    const title = buildTitle(category, localIndex, id);
    const author = buildAuthor(id);
    const localPreview = buildLocalPreviewPath(id);
    const date = DATES[id % DATES.length];
    return {
      id,
      title,
      author,
      avatar: buildAvatar(author),
      duration: formatDuration(durationPool[id]),
      views: buildViews(id, title, date),
      date,
      quality: QUALS[id % QUALS.length],
      category,
      categoryLabel: CATEGORY_THEMES[category].label,
      previewStatic: localPreview,
      previewFallbackStatic: localPreview,
      playerExcerpt: buildPlayerExcerpt(title, author, category, id)
    };
  });

  const AUTHORS = ALL_CARDS.map((card) => card.author);

  function buildPlayerUrl(cardId) {
    return `/video/${encodeURIComponent(cardId)}`;
  }

  function buildChannelUrl(author) {
    return `/channel/${encodeURIComponent(author)}`;
  }

  function findCardById(cardId) {
    return ALL_CARDS.find((card) => String(card.id) === String(cardId)) || ALL_CARDS[0];
  }

  function findCardsByAuthor(author) {
    return ALL_CARDS.filter((card) => card.author === author);
  }

  window.REMOVI_DATA = {
    ALL_CARDS,
    AUTHORS,
    CATEGORY_THEMES,
    DEFAULT_MESSAGES,
    FILTERS,
    SETTINGS,
    buildChannelUrl,
    buildLocalPreviewPath,
    buildPlayerUrl,
    buildPreviewSvgMarkup,
    clampText,
    escapeHtml,
    findCardById,
    findCardsByAuthor,
    normalizeText,
    shuffle
  };
})();
